[package]
name = "scenes"
version = {workspace = true}
edition = {workspace = true}

[dependencies]
geometry = {path = "../geometry"}
shared = {path = "../shared"}
rand = { workspace = true }
serde = { version = "1.0.152", features = ["derive"] }

[dev-dependencies]
toml = "0.7.2"

[features]
debug = ["shared/debug", "geometry/debug"]
euclid = ["shared/euclid", "geometry/euclid"]

[lints]
workspace = true
