[package]
name = "scenes"
version = {workspace = true}
edition = {workspace = true}

[dependencies]
geometry = {path = "../geometry"}
shared = {path = "../shared"}
rand = { workspace = true }

[features]
debug = ["shared/debug", "geometry/debug"]
euclid = ["shared/euclid", "geometry/euclid"]

[lints]
workspace = true
