version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    open-pull-requests-limit: 1
    rebase-strategy: auto
    versioning-strategy: lockfile-only
    schedule:
      interval: monthly
