
[workspace]
resolver = '3'
members = [
    "bin", "geometry",
    "shared", "integration-tests",
]

[workspace.package]
edition = "2024"
version = "0.1.0"

[workspace.lints.clippy]
missing_const_for_fn = "deny"
pedantic = { level = "warn", priority = 1}
perf = {level = "warn", priority = 1}
cognitive_complexity = {level = "warn", priority = 1}
empty_line_after_outer_attr = "warn"
needless_borrow = "warn"
wrong_self_convention = "warn"
cast_precision_loss = { level = "allow", priority = 2}

[workspace.dependencies]
rand = { version = "0.8.5", features = ["small_rng"] }
bumpalo = {version = "3.20.3", features = ["allocator_api"]}

[profile.dev]
opt-level = 0


[profile.dev.package."*"]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.bench]
debug = true

[profile.release]
debug = true
lto = "fat"
panic = "abort"

[profile.release.build-override]
opt-level = 3
