name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose && cargo build --verbose --features=euclid
      - name: Clippy
        run: cargo clippy --verbose && cargo clippy --verbose --features=euclid
      - name: Run tests
        run: cargo test --verbose && cargo test --verbose --features=euclid
      - name: Run Miri
        run: cargo miri test --verbose
